In [35]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [36]:
dataset=pd.read_csv('insurance_pre.csv')

In [37]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [38]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [39]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [40]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [41]:
independent=dataset[['age', 'bmi', 'children',  'sex_male', 'smoker_yes']]

In [42]:
dependent=dataset[['charges']]

In [43]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [44]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [45]:
X_train

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]])

In [46]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

In [47]:
param_grid={'criterion':['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],'max_features':['sqrt', 'log2'], 'n_estimators':[10,100,100]}

In [48]:
grid=GridSearchCV(RandomForestRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)

In [49]:
grid=grid.fit(X_train,y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Anaconda3\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [50]:
re=grid.cv_results_

In [51]:
re

{'mean_fit_time': array([0.07124519, 0.45372572, 0.44322991, 0.05616813, 0.43446221,
        0.43200989, 0.12965822, 1.22602153, 1.53703785, 0.14652224,
        2.37213802, 2.57459006, 0.13270311, 0.92287321, 0.94118543,
        0.11850219, 0.93661938, 0.93845401, 0.11570363, 1.03132787,
        1.07667861, 0.11529446, 1.06544795, 0.89233465]),
 'std_fit_time': array([0.00340466, 0.0150965 , 0.00823301, 0.00636731, 0.01357724,
        0.00776532, 0.00788516, 0.0275438 , 0.37685417, 0.01233925,
        0.12327721, 0.22773165, 0.02172541, 0.01222321, 0.00863436,
        0.01085863, 0.01857805, 0.01261109, 0.00300749, 0.01835067,
        0.04436957, 0.00873187, 0.02641134, 0.06119945]),
 'mean_score_time': array([0.00753675, 0.01446176, 0.01559324, 0.00498919, 0.02057557,
        0.01444254, 0.0038847 , 0.01775794, 0.02258306, 0.00372906,
        0.03631577, 0.0354547 , 0.01180129, 0.03781972, 0.03663516,
        0.01111555, 0.03680811, 0.03447266, 0.01264691, 0.04191914,
        0.03754959, 0.0097393 , 0.03856716, 0.02881918]),
 'std_score_time': array([0.00235391, 0.00277259, 0.00174566, 0.00153098, 0.00200239,
        0.00305968, 0.00220459, 0.00589843, 0.00753038, 0.00197224,
        0.00548112, 0.00325509, 0.00337128, 0.00271453, 0.00462369,
        0.00263884, 0.00429847, 0.00223294, 0.00452438, 0.00606934,
        0.00288555, 0.00050521, 0.00216148, 0.00174904]),
 'param_criterion': masked_array(data=['squared_error', 'squared_error', 'squared_error',
                    'squared_error', 'squared_error', 'squared_error',
                    'absolute_error', 'absolute_error', 'absolute_error',
                    'absolute_error', 'absolute_error', 'absolute_error',
                    'friedman_mse', 'friedman_mse', 'friedman_mse',
                    'friedman_mse', 'friedman_mse', 'friedman_mse',
                    'poisson', 'poisson', 'poisson', 'poisson', 'poisson',
                    'poisson'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_max_features': masked_array(data=['sqrt', 'sqrt', 'sqrt', 'log2', 'log2', 'log2', 'sqrt',
                    'sqrt', 'sqrt', 'log2', 'log2', 'log2', 'sqrt', 'sqrt',
                    'sqrt', 'log2', 'log2', 'log2', 'sqrt', 'sqrt', 'sqrt',
                    'log2', 'log2', 'log2'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_n_estimators': masked_array(data=[10, 100, 100, 10, 100, 100, 10, 100, 100, 10, 100, 100,
                    10, 100, 100, 10, 100, 100, 10, 100, 100, 10, 100, 100],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'criterion': 'squared_error',
   'max_features': 'sqrt',
   'n_estimators': 10},
  {'criterion': 'squared_error', 'max_features': 'sqrt', 'n_estimators': 100},
  {'criterion': 'squared_error', 'max_features': 'sqrt', 'n_estimators': 100},
  {'criterion': 'squared_error', 'max_features': 'log2', 'n_estimators': 10},
  {'criterion': 'squared_error', 'max_features': 'log2', 'n_estimators': 100},
  {'criterion': 'squared_error', 'max_features': 'log2', 'n_estimators': 100},
  {'criterion': 'absolute_error', 'max_features': 'sqrt', 'n_estimators': 10},
  {'criterion': 'absolute_error', 'max_features': 'sqrt', 'n_estimators': 100},
  {'criterion': 'absolute_error', 'max_features': 'sqrt', 'n_estimators': 100},
  {'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 10},
  {'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 100},
  {'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 100},
  {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'n_estimators': 10},
  {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'n_estimators': 100},
  {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'n_estimators': 100},
  {'criterion': 'friedman_mse', 'max_features': 'log2', 'n_estimators': 10},
  {'criterion': 'friedman_mse', 'max_features': 'log2', 'n_estimators': 100},
  {'criterion': 'friedman_mse', 'max_features': 'log2', 'n_estimators': 100},
  {'criterion': 'poisson', 'max_features': 'sqrt', 'n_estimators': 10},
  {'criterion': 'poisson', 'max_features': 'sqrt', 'n_estimators': 100},
  {'criterion': 'poisson', 'max_features': 'sqrt', 'n_estimators': 100},
  {'criterion': 'poisson', 'max_features': 'log2', 'n_estimators': 10},
  {'criterion': 'poisson', 'max_features': 'log2', 'n_estimators': 100},
  {'criterion': 'poisson', 'max_features': 'log2', 'n_estimators': 100}],
 'split0_test_score': array([0.84738561, 0.86126589, 0.86023881, 0.84302367, 0.8628781 ,
        0.86718455, 0.83849923, 0.85359824, 0.85869574, 0.83970299,
        0.85931545, 0.85502686, 0.80745261, 0.85918035, 0.86110203,
        0.84657335, 0.86704278, 0.86372879, 0.81931679, 0.86095731,
        0.85981731, 0.85579934, 0.85775477, 0.85643727]),
 'split1_test_score': array([0.76128701, 0.78708364, 0.7934093 , 0.78469224, 0.78697624,
        0.79234019, 0.77972534, 0.79173934, 0.7988646 , 0.77303679,
        0.79364069, 0.79205259, 0.75630763, 0.78145553, 0.7940428 ,
        0.73956269, 0.78887653, 0.79585287, 0.77016973, 0.79478767,
        0.79061596, 0.73710842, 0.79736994, 0.79547365]),
 'split2_test_score': array([0.77406906, 0.80521489, 0.81003392, 0.79076691, 0.80610693,
        0.81050804, 0.79379248, 0.81221716, 0.8014274 , 0.77632715,
        0.81016191, 0.80274695, 0.79839909, 0.80749895, 0.80968708,
        0.79482932, 0.80732988, 0.81011863, 0.78477947, 0.81212841,
        0.79787084, 0.78919875, 0.81020772, 0.81194345]),
 'split3_test_score': array([0.81992569, 0.82520236, 0.82893559, 0.80056543, 0.82910197,
        0.83185058, 0.77501827, 0.82590741, 0.82405172, 0.80880403,
        0.82569951, 0.82803287, 0.80780886, 0.82716231, 0.83575104,
        0.8192511 , 0.82490384, 0.83385972, 0.79553122, 0.82905724,
        0.83057945, 0.79605635, 0.82603873, 0.83065286]),
 'split4_test_score': array([0.77545534, 0.76875992, 0.76798126, 0.73847412, 0.77309226,
        0.7740916 , 0.72527752, 0.76997098, 0.7739544 , 0.74618005,
        0.77447999, 0.76689639, 0.74167768, 0.77100482, 0.77335023,
        0.71501628, 0.76886824, 0.76870803, 0.7615667 , 0.77316975,
        0.76896542, 0.74219117, 0.76924093, 0.76662486]),
 'mean_test_score': array([0.79562454, 0.80950534, 0.81211978, 0.79150448, 0.8116311 ,
        0.81519499, 0.78246257, 0.81068663, 0.81139877, 0.7888102 ,
        0.81265951, 0.80895114, 0.78232917, 0.80926039, 0.81478663,
        0.78304655, 0.81140425, 0.81445361, 0.78627279, 0.81402007,
        0.8095698 , 0.78407081, 0.81212242, 0.81222642]),
 'std_test_score': array([0.0326198 , 0.03195897, 0.03130768, 0.03345294, 0.03179656,
        0.03229279, 0.03633597, 0.02860834, 0.02848057, 0.03228555,
        0.02888753, 0.03026463, 0.02781478, 0.03178737, 0.03084772,
        0.04899841, 0.03350014, 0.03244096, 0.02024625, 0.02990463,
        0.03197201, 0.04306809, 0.0294486 , 0.03051023]),
 'rank_test_score': array([17, 14,  8, 18,  9,  1, 23, 12, 11, 19,  5, 16, 24, 15,  2, 22, 10,
         3, 20,  4, 13, 21,  7,  6])}

In [54]:
y_pred=grid.predict(X_test)

In [56]:
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'squared_error', 'max_features': 'log2', 'n_estimators': 100}:

In [58]:
table=pd.DataFrame.from_dict(re)

In [59]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.071245,0.003405,0.007537,0.002354,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.847386,0.761287,0.774069,0.819926,0.775455,0.795625,0.032620,17
1,0.453726,0.015096,0.014462,0.002773,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.861266,0.787084,0.805215,0.825202,0.768760,0.809505,0.031959,14
2,0.443230,0.008233,0.015593,0.001746,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.860239,0.793409,0.810034,0.828936,0.767981,0.812120,0.031308,8
3,0.056168,0.006367,0.004989,0.001531,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.843024,0.784692,0.790767,0.800565,0.738474,0.791504,0.033453,18
4,0.434462,0.013577,0.020576,0.002002,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.862878,0.786976,0.806107,0.829102,0.773092,0.811631,0.031797,9
5,0.432010,0.007765,0.014443,0.003060,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.867185,0.792340,0.810508,0.831851,0.774092,0.815195,0.032293,1
6,0.129658,0.007885,0.003885,0.002205,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.838499,0.779725,0.793792,0.775018,0.725278,0.782463,0.036336,23
7,1.226022,0.027544,0.017758,0.005898,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.853598,0.791739,0.812217,0.825907,0.769971,0.810687,0.028608,12
8,1.537038,0.376854,0.022583,0.007530,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.858696,0.798865,0.801427,0.824052,0.773954,0.811399,0.028481,11
9,0.146522,0.012339,0.003729,0.001972,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.839703,0.773037,0.776327,0.808804,0.746180,0.788810,0.032286,19
10,2.372138,0.123277,0.036316,0.005481,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.859315,0.793641,0.810162,0.825700,0.774480,0.812660,0.028888,5
11,2.574590,0.227732,0.035455,0.003255,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.855027,0.792053,0.802747,0.828033,0.766896,0.808951,0.030265,16
12,0.132703,0.021725,0.011801,0.003371,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.807453,0.756308,0.798399,0.807809,0.741678,0.782329,0.027815,24
13,0.922873,0.012223,0.037820,0.002715,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.859180,0.781456,0.807499,0.827162,0.771005,0.809260,0.031787,15
14,0.941185,0.008634,0.036635,0.004624,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.861102,0.794043,0.809687,0.835751,0.773350,0.814787,0.030848,2
15,0.118502,0.010859,0.011116,0.002639,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.846573,0.739563,0.794829,0.819251,0.715016,0.783047,0.048998,22
16,0.936619,0.018578,0.036808,0.004298,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.867043,0.788877,0.807330,0.824904,0.768868,0.811404,0.033500,10
17,0.938454,0.012611,0.034473,0.002233,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.863729,0.795853,0.810119,0.833860,0.768708,0.814454,0.032441,3
18,0.115704,0.003007,0.012647,0.004524,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.819317,0.770170,0.784779,0.795531,0.761567,0.786273,0.020246,20
19,1.031328,0.018351,0.041919,0.006069,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.860957,0.794788,0.812128,0.829057,0.773170,0.814020,0.029905,4
20,1.076679,0.044370,0.037550,0.002886,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.859817,0.790616,0.797871,0.830579,0.768965,0.809570,0.031972,13
21,0.115294,0.008732,0.009739,0.000505,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.855799,0.737108,0.789199,0.796056,0.742191,0.784071,0.043068,21
22,1.065448,0.026411,0.038567,0.002161,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.857755,0.797370,0.810208,0.826039,0.769241,0.812122,0.029449,7
23,0.892335,0.061199,0.028819,0.001749,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.856437,0.795474,0.811943,0.830653,0.766625,0.812226,0.030510,6

In [60]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 23
BMI: 24
Children: 2
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1

In [61]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[48555.6005292]

In [62]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [63]:
r_score

0.8616871063396023

In [64]:
import pickle

In [67]:
filename="final_model_RFR.sav"

In [68]:
pickle.dump(grid,open(filename,'wb'))

In [72]:
loaded_model=pickle.load(open("final_model_RFR.sav",'rb'))

In [73]:
result=loaded_model.predict([[24,34,0,1,1]])

In [74]:
result

array([47662.5237879])